In [6]:
import numpy as np

sal_estagiario = [1000, 1500, 500, 600]
array_sal_estagio = np.array(sal_estagiario)

salarios = np.array([3000,2500,3500,4000,4500,5000])


#calcular media de salarios
media_salarial = np.mean(salarios)

print(media_salarial)



#retorna o array com indices dos valores acima da media
funcionarios_acima_media = np.where(salarios > media_salarial)

print(funcionarios_acima_media)

#numpy aceita receber um array de indices
print(salarios[funcionarios_acima_media])

#se for uma condição simples nao precia do where
print(salarios[salarios>media_salarial])
print(salarios[salarios>4000])


3750.0
(array([3, 4, 5], dtype=int64),)
[4000 4500 5000]
[4000 4500 5000]
[4500 5000]


In [9]:

media_sal = sum(sal_estagiario) / len(sal_estagiario)
print(media_sal)

for i in range(len(sal_estagiario)):
  if sal_estagiario[i] > media_sal:
    print(sal_estagiario[i])

print(array_sal_estagio[array_sal_estagio>np.mean(array_sal_estagio)])




900.0
1000
1500
[1000 1500]


In [15]:

#cria outro array de aacordo coma condição passada
print((np.where(salarios > media_salarial, "Acima da media","Abaixo da media")))

#ajustando o valor de quem recebe entre 400 e 999 em 5%
#                                 condição                                              se sim                          se não
salarios_ajustados = np.where((array_sal_estagio > 400) & (array_sal_estagio < 1000), array_sal_estagio * 1.05, array_sal_estagio)
print(salarios_ajustados)

#ajustando salario menor que 600 e maior que 1000
salarios_ajustados = np.where((array_sal_estagio < 600) | (array_sal_estagio > 1000), array_sal_estagio * 1.05, array_sal_estagio)
print(salarios_ajustados)


['Abaixo da media' 'Abaixo da media' 'Abaixo da media' 'Acima da media'
 'Acima da media' 'Acima da media']
[1000. 1500.  525.  630.]
[1000. 1575.  525.  600.]
